services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - DEBUG=1
      - AWS_DEFAULT_REGION=ca-central-1
    volumes:
      - "./.localstack:/var/lib/localstack"
